server:
  port: 8268
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000

spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    locale: zh_CN
  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB # 单个文件最大尺寸
      max-request-size: 150MB # 多文件上传时，最大上传尺寸

logging:
  level:
    root: info
  file:
    path: ./logs